version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-frontend-js
    ports:
      - "3000:3000"

    depends_on:
      - db

    environment:
      PORT: 3000

volumes:
  db_data:
    driver: local